#!/usr/bin/env bash
#
# TRUSTED apply step for the Managed Agents autofix loop. Reads the git patch the
# agent wrote to its outputs dir (/mnt/session/outputs/fix.patch, surfaced on the
# host by spawn.sh under $OUTPUTS_ROOT/<session>/), applies it to a fresh branch,
# and — only when APPLY_OPEN_PR=true — pushes and opens a PR.
#
# This runs OUTSIDE the agent sandbox: it is the only place that holds repo-write
# credentials. The agent produces a diff; a trusted actor reviews-then-applies it.
# The resulting PR re-runs the normal CI gate and awaits human review (no auto-merge).
#
# Usable locally too: leave APPLY_OPEN_PR unset to just apply the patch to a branch
# in your working copy (no push, no PR) so you can inspect the agent's fix.
set -euo pipefail

OUTPUTS_ROOT="${OUTPUTS_ROOT:-/tmp/vector-rs-sessions}"
PATCH="$(ls -t "$OUTPUTS_ROOT"/*/fix.patch 2>/dev/null | head -1 || true)"

if [ -z "$PATCH" ]; then
  echo "No fix.patch found under $OUTPUTS_ROOT — the agent proposed no change. Nothing to apply."
  exit 0
fi
echo "Applying agent patch: $PATCH"

# Validate it applies cleanly before touching any branch.
if ! git apply --check "$PATCH" 2>/dev/null; then
  echo "❌ Patch does not apply cleanly against the current tree — not applying." >&2
  exit 1
fi

BASE_SHA="${AUTOFIX_BASE_SHA:-$(git rev-parse --short HEAD)}"
BRANCH="autofix/ci-${BASE_SHA:0:8}"
git checkout -B "$BRANCH"
git apply --index "$PATCH"
git -c user.name="vector-rs-autofix" -c user.email="autofix@users.noreply.github.com" \
  commit -m "autofix: proposed fix for failing vector-rs build

Generated by a Managed Agents session and validated in the worker sandbox
(cargo test) before this patch was surfaced. Review before merging."

if [ "${APPLY_OPEN_PR:-}" != "true" ]; then
  echo "✅ Applied to branch '$BRANCH' (local mode; not pushed). Inspect with: git show"
  exit 0
fi

# Push + open PR (trusted creds only). A PR opened by GITHUB_TOKEN does not itself
# retrigger workflow_run, which conveniently prevents an autofix→fail→autofix loop;
# the normal push CI (build-test) still runs on the branch.
for i in 1 2 3 4; do
  git push -u origin "$BRANCH" && break
  echo "push failed, retry $i"; sleep $((2 ** i))
done

if command -v gh >/dev/null 2>&1; then
  gh pr create --base main --head "$BRANCH" \
    --title "autofix: fix failing vector-rs build ($BASE_SHA)" \
    --body "Proposed by a Managed Agents session; validated with \`cargo test\` in the worker sandbox before the patch was surfaced. The agent had no repo-write access — this PR was opened by the trusted apply step. Please review before merging."
else
  echo "gh not available; branch pushed. Open a PR from '$BRANCH' manually."
fi
